### ISSUE TITLE
Green Tea crates

### ISSUE THREAD

**Issue by itsdeadfrosty** [pouffy/Bundled-Delights#2]
Hey, for some reason tea crates are not dropping when broken. Not sure why. Kind of makes me not wanna use them for obvious reasons.

Tested with diamond, pickaxe, hoe, axe and shovel as well as bare hands.

**Comment by pouffy** [comment]
Oh my god I forgot to set up a loot table datagen

**Comment by pouffy** [comment]
Should be fixed in the new version
https://curseforge.com/minecraft/mc-mods/bundled-delight/files/4527176

**Comment by itsdeadfrosty** [comment]
It was kinda funny, I was like huh?? Thank you, glad I could help :)On May 7, 2023, at 13:09, Pouffy ***@***.***> wrote:﻿
Should be fixed in the new version
https://curseforge.com/minecraft/mc-mods/bundled-delight/files/4527176
